#!/bin/sh

: ${lbu:=/opt/LiveBootUtils}
. "$lbu/scripts/common.func"

: ${jre_url:=http://javadl.oracle.com/webapps/download/AutoDL?BundleId=216424}

: ${jre_tgz:=$(dl_file "$jre_url")}

tar xfz "$jre_tgz" -C "$DESTDIR/opt" --no-same-owner

java_topdir="$(tar tfz "$jre_tgz" | head -1 | tr -d /)"

ln -s "$java_topdir" "$DESTDIR/opt/jre"

find "$DESTDIR/opt/jre/bin" -mindepth 1 -maxdepth 1 -perm +1 -exec sh -c 'for f;do ln -s _jre_exec.sh "$DESTDIR/opt/bin/${f##*/}";done' _ {} +
